export const FullCurrencyName = {
    CAD: "Canadian Dollar",
    HKD: "Hong Kong Dollar",
    ISK: "Icelandic Króna",
    PHP: "Philippine Peso",
    DKK: "Danish Krone",
    HUF: "Hungarian Forint",
    CZK: "Czech Koruna",
    GBP: "British Pound",
    RON: "Romanian Leu",
    SEK: "Swedish Krona",
    IDR: "Indonesian Rupiah",
    INR: "Indian Rupee",
    BRL: "Brazilian Real",
    RUB: "Russian Ruble",
    HRK: "Croatian Kuna",
    JPY: "Japanese Yen",
    THB: "Thai Baht",
    CHF: "Swiss Franc",
    EUR: "Euro",
    MYR: "Malaysian Ringgit",
    BGN: "Bulgarian Lev",
    TRY: "Turkish Lira",
    CNY: "Chinese Yuan",
    NOK: "Norwegian Krone",
    NZD: "New Zealand Dollar",
    ZAR: "South African Rand",
    USD: "US Dollar",
    MXN: "Mexican Peso",
    SGD: "Singapore Dollar",
    AUD: "Australian Dollar",
    ILS: "Israeli New Shekel",
    KRW: "South Korean Won",
    PLN: "Poland Złoty" 
};

export const FlagIcon = {
    CAD: "/flags/canada.svg",
    HKD: "/flags/hong-kong.svg",
    ISK: "/flags/iceland.svg",
    PHP: "/flags/philippines.svg",
    DKK: "/flags/denmark.svg",
    HUF: "/flags/hungary.svg",
    CZK: "/flags/czech-republic.svg",
    GBP: "/flags/united-kingdom.svg",
    RON: "/flags/romania.svg",
    SEK: "/flags/sweden.svg",
    IDR: "/flags/indonesia.svg",
    INR: "/flags/india.svg",
    BRL: "/flags/brazil.svg",
    RUB: "/flags/russia.svg",
    HRK: "/flags/croatia.svg",
    JPY: "/flags/japan.svg",
    THB: "/flags/thailand.svg",
    CHF: "/flags/switzerland.svg", 
    EUR: "/flags/european-union.svg",
    MYR: "/flags/malaysia.svg",
    BGN: "/flags/bulgaria.svg",
    TRY: "/flags/turkey.svg",
    CNY: "/flags/china.svg",
    NOK: "/flags/norway.svg",
    NZD: "/flags/new-zealand.svg",
    ZAR: "/flags/south-africa.svg",
    USD: "/flags/united-states.svg",
    MXN: "/flags/mexico.svg",
    SGD: "/flags/singapore.svg",
    AUD: "/flags/australia.svg",
    ILS: "/flags/israel.svg",
    KRW: "/flags/south-korea.svg",
    PLN: "/flags/poland.svg",
};

export const CurrencyList = [
    "AUD",
    "USD",
    "EUR",
    "JPY",
    "GBP",
    "CAD",
    "CHF",
    "CNH",
    "SEK",
    "NZD"
]