export const FullCurrencyName = {
    CAD: "Canadian Dollar",
    HKD: "Hong Kong Dollar",
    ISK: "Icelandic Króna",
    PHP: "Philippine Peso",
    DKK: "Danish Krone",
    HUF: "Hungarian Forint",
    CZK: "Czech Koruna",
    GBP: "British Pound Sterling",
    RON: "Romanian Leu",
    SEK: "Swedish Krona",
    IDR: "Indonesian Rupiah",
    INR: "Indian Rupee",
    BRL: "Brazilian Real",
    RUB: "Russian Ruble",
    HRK: "Croatian Kuna",
    JPY: "Japanese Yen",
    THB: "Thai Baht",
    CHF: "Swiss Franc",
    EUR: "Euro",
    MYR: "Malaysian Ringgit",
    BGN: "Bulgarian Lev",
    TRY: "Turkish Lira",
    CNY: "Chinese Yuan",
    NOK: "Norwegian Krone",
    NZD: "New Zealand Dollar",
    ZAR: "South African Rand",
    USD: "US Dollar",
    MXN: "Mexican Peso",
    SGD: "Singapore Dollar",
    AUD: "Australian Dollar",
    ILS: "Israeli New Shekel",
    KRW: "South Korean Won",
    PLN: "Poland Złoty" 
};

export const CurrencyList = [
    "AUD",
    "USD",
    "EUR",
    "JPY",
    "GBP",
    "CAD",
    "CHF",
    "CNH",
    "SEK",
    "NZD"
]