export const Currency = {
    CAD: ["Canadian Dollar",    "/flags/canada.svg",         "$"],
    HKD: ["Hong Kong Dollar",   "/flags/hong-kong.svg",      "$"],
    ISK: ["Icelandic Króna",    "/flags/iceland.svg",        "kr"],
    PHP: ["Philippine Peso",    "/flags/philippines.svg",    "\u20B1"],
    DKK: ["Danish Krone",       "/flags/denmark.svg",        "kr"],
    HUF: ["Hungarian Forint",   "/flags/hungary.svg",        "Ft"],
    CZK: ["Czech Koruna",       "/flags/czech-republic.svg", "K\u010D"],
    GBP: ["British Pound",      "/flags/united-kingdom.svg", "\u00A3"],
    RON: ["Romanian Leu",       "/flags/romania.svg",        "lei"],
    SEK: ["Swedish Krona",      "/flags/sweden.svg",         "kr"],
    IDR: ["Indonesian Rupiah",  "/flags/indonesia.svg",      "Rp"],
    INR: ["Indian Rupee",       "/flags/india.svg",          "\u20B9"],
    BRL: ["Brazilian Real",     "/flags/brazil.svg",         "R$"],
    RUB: ["Russian Ruble",      "/flags/russia.svg",         "\u20BD"],
    HRK: ["Croatian Kuna",      "/flags/croatia.svg",        "kn"],    
    JPY: ["Japanese Yen",       "/flags/japan.svg",          "\u00A5"],    
    THB: ["Thai Baht",          "/flags/thailand.svg",       "\u0E3F"],    
    CHF: ["Swiss Franc",        "/flags/switzerland.svg",    "Fr"],    
    EUR: ["Euro",               "/flags/european-union.svg", "\u20AC"],    
    MYR: ["Malaysian Ringgit",  "/flags/malaysia.svg",       "RM"],    
    BGN: ["Bulgarian Lev",      "/flags/bulgaria.svg",       "\u043BB"],    
    TRY: ["Turkish Lira",       "/flags/turkey.svg",         "\u20BA"],        
    CNY: ["Chinese Yuan",       "/flags/china.svg",          "\u00A5"],    
    NOK: ["Norwegian Krone",    "/flags/norway.svg",         "kr"],    
    NZD: ["New Zealand Dollar", "/flags/new-zealand.svg",    "$"],        
    ZAR: ["South African Rand", "/flags/south-africa.svg",   "R"],        
    USD: ["US Dollar",          "/flags/united-states.svg",  "$"],        
    MXN: ["Mexican Peso",       "/flags/mexico.svg",         "$"],    
    SGD: ["Singapore Dollar",   "/flags/singapore.svg",      "$"],    
    AUD: ["Australian Dollar",  "/flags/australia.svg",      "$"],    
    ILS: ["Israeli New Shekel", "/flags/israel.svg",         "\u20aa"],
    KRW: ["South Korean Won",   "/flags/south-korea.svg",    "\u20a9"],
    PLN: ["Poland Złoty",       "/flags/poland.svg",         "z\u0142"]
};

export const CurrencyList = [
    "AUD",
    "USD",
    "EUR",
    "JPY",
    "GBP",
    "CAD",
    "CHF",
    "CNH",
    "SEK",
    "NZD"
]